namespace Randomizer.SMZ3.FileData
{
    public enum ALttPSoundtrack : byte
    {
        None = 0,
        Title = 1,
        LightWorldOverworld = 2,
        Rain = 3,
        Bunny = 4,
        LightLostWoods = 5,
        OpeningStoryCredits = 6,
        KakarikoVillage = 7,
        Mirror = 8,
        DarkWorldOverworld = 9,
        MasterSwordPedestal = 10,
        FileSelect = 11,
        GuardSummonedInKakarikoVillage = 12,
        DarkDeathMountain = 13,
        GuessingGame = 14,
        HyruleCastle = 16,
        LightWorldDungeon = 17,
        Cave1 = 18,
        BossKillFanfare = 19,
        Sanctuary = 20,
        BossFight = 21,
        DarkWorldDungeon = 22,
        FortuneTeller = 23,
        Cave2 = 24,
        ZeldaRescued = 25,
        CrystalGet = 26,
        FairyFountain = 27,
        GanonsTheme = 28,
        GanonAppears = 29,
        GanonInPyramid = 30,
        GanonFight = 31,
        TriforceRoom = 32,
        TriumphantReturn = 33,
        Credits = 34,
    }
}
